const abi = [
  // Validatable
  "function InsufficientBalance(uint256, uint256)",
  "function InValidOrderContract(address)",
  "function InValidMetaversusManagerContract(address)",
  "function InValidTokenCollectionERC721Contract(address)",
  "function InValidTokenCollectionERC1155Contract(address)",
  "function InValidAdminContract(address)",
  "function InValidTokenMintERC721Contract(address)",
  "function InValidTokenMintERC1155Contract(address)",
  "function InValidTreasuryContract(address)",
  "function InValidMarketplaceManagerContract(address)",
  "function InValidCollectionFactoryContract(address)",
  "function InValidStakingPoolContract(address)",
  "function InValidMetaCitizenContract(address)",
  "function InvalidAddress()",
  "function InvalidAmount()",
  "function PaymentTokenIsNotSupported()",
  "function InvalidWallet(address)",
  "function CallerIsNotOwnerOrAdmin()",
  "function CallerIsNotOwner()",
  // Order Manager
  "function InvalidMarketItemId()",
  "function InvalidNftAddress(address)",
  "function InvalidOrderTime()",
  "function InvalidOwner(address)",
  "function UserCanNotOffer()",
  "function InvalidTokenId(uint256)",
  "function CanNotUpdatePaymentToken()",
  "function MarketItemIsNotAvailable()",
  "function NotInTheOrderTime()",
  "function RequireOwneMetaCitizenNFT()",
  "function InvalidOrderId()",
  "function NotTheSeller(address, address)",
  "function NotTheOwnerOfOrder(address, address)",
  "function OrderIsNotAvailable()",
  "function OrderIsExpired()",
  "function NotExpiredYet()",
  "function InvalidEndTime()",
  "function TokenIsNotExisted(address, uint256)",
  "function CanNotBuyYourNFT()",
  "function MarketItemIsNotSelling()",
  "function EitherNotInWhitelistOrNotOwnMetaCitizenNFT()",
  // Metaversus manager
  "function UserDidNotCreateCollection()",
  "function InvalidNFTAddress(address)",
  // MarketPlace manager
  "function InvalidTimeForCreate()",
  "function CallerIsNotOrderManager()",
  "function CallerIsNotOrderManagerOrMTVSManager()",
  // MetaDrop
  "function InvalidDropId()",
  "function ServiceFeeExceedMintFee()",
  "function InvalidRoot()",
  "function InvalidMintingSupply()",
  "function InvalidFundingReceiver()",
  "function InvalidOwnerForUpdate()",
  "function DropIsCanceled()",
  "function NotPermitToMintNow()",
  "function CanNotMintAnyMore()",
  "function NotEnoughFee()",
  "function NotPayBothToken()",
  // Collection
  "function ExceedMaxCollection()",
  "function CloneCollectionFailed()",
  "function InvalidMaxCollection()",
  "function InvalidMaxTotalSupply()",
  "function InvalidMaxCollectionOfUser()",
  // Token721
  "function CallerIsNotFactory()",
  "function ExceedTotalSupply()",
  "function ExceedMaxMintBatch()",
  "function InvalidMaxBatch()",
  "function URIQueryNonExistToken()",
  // Token1155
  "function InvalidArrayInput()",
  // Pool Factory
  "function ClonePoolFailed()",
  // Staking
  "function NotAllowToClaim()",
  "function NotTimeForStake()",
  "function AlreadyRequested()",
  "function OverLimit()",
  "function NotAllowToUnstake()",
  "function MustRequestFirst()",
  "function ExceedAmount()",
  "function MustStakeMoreThan500Dollar()",
  "function MustBuyNFTInMarketplaceFirst()",
  // NFT
  "function InvalidPaymentToken()",
  "function AlreadyHaveOne()",
  "function CanNotBeTransfered()",
  "function InvalidLength()",
  "function AlreadyRegister()",
  "function FailToSendIntoContract()",
  "function TransferNativeFail()",
  "function NotTheOwnerOfOffer()"
];

module.exports = {
  abi
};
